version: '3'

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - elasticdata:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    depends_on:
      - elastic
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data
    networks:
      - elastic

networks:
  elastic: