version: '3'

services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    container_name: cadvisor
    volumes:
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/sys:/sys:ro'
      - '/var/run:/var/run:rw'
      - '/:/rootfs:ro'

    networks:
      - supervision
    devices:
      - /dev/kmsg:/dev/kmsg
    privileged: true

  grafana:
    image: grafana/grafana-enterprise:8.2.0
    user: 1000:1000
    networks:
      - supervision
    volumes:
      - /srv/grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    volumes:
      - /srv/prometheus/:/etc/prometheus/
    networks:
      - supervision

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'